apiVersion: 1.0.0
kind: Plugin
metadata:
  name: Couchbase Storage
  description: Couchbase storage plugin for Reekoh IoT Platform.
  documentation: README.md
  icon: asset/icon/reekoh200x200.png
  signupLink: https://myservice.com/signup # ??
  type: Storage
  price: 0
  tags:
    - storage
    - couchbase
  config:
    host:
      label: Host
      type: String
      maxLength: 1000
      required: true
      help: "Host for the Couchbase database connection."
    port:
      label: Port
      type: Number
      min: 1
      max: 65353
      required: false
      help: "(Optional) Port for the Couchbase database connection."
    bucket:
      label: Bucket
      type: String
      maxLength: 1000
      required: true
      help: "Bucket where the data will be saved."
    bucketPassword:
      label: Bucket Password
      type: Password
      maxLength: 1000
      required: false
      help: "(Optional) Bucket Password for authentication."
    transactionType:
      label: Transaction Type
      type: String
      maxLength: 1000
      required: true
      help: "Type of transaction process when inserting data."
    keyField:
      label: Key Field
      type: String
      maxLength: 1000
      required: true
      help: "(Optional) Use this field to assign the key. If this is blank or if the field is not found within the data, the key will be generated automatically."

  release:
    version: 1.0.0
    notes: path/to/RELEASENOTESv1.0.0.md # ??
    image: path/to/docker/image # ??